-- Category
INSERT INTO category VALUES (1, "Horreur");

-- Programs
insert into program (id, title, synopsis, poster, category_id, country, year) values (1, 'Walking Dead', 'Le policier Rick Grimes se réveille après un long coma. Il découvre avec effarement que le monde, ravagé par une épidémie, est envahi par les morts-vivants.', 'https://m.media-amazon.com/images/M/MV5BZmFlMTA0MmUtNWVmOC00ZmE1LWFmMDYtZTJhYjJhNGVjYTU5XkEyXkFqcGdeQXVyMTAzMDM4MjM0._V1_.jpg', 1, '', 0);
insert into program (id, title, synopsis, poster, category_id, country, year) values (2, 'The Haunting Of Hill House', 'Plusieurs frères et sœurs qui, enfants, ont grandi dans la demeure qui allait devenir la maison hantée la plus célèbre des États-Unis, sont contraints de se réunir pour finalement affronter les fantômes de leur passé.', 'https://m.media-amazon.com/images/M/MV5BMTU4NzA4MDEwNF5BMl5BanBnXkFtZTgwMTQxODYzNjM@._V1_SY1000_CR0,0,674,1000_AL_.jpg', 1, '', 0);
insert into program (id, title, synopsis, poster, category_id, country, year) values (3, 'American Horror Story', 'A chaque saison, son histoire. American Horror Story nous embarque dans des récits à la fois poignants et cauchemardesques, mêlant la peur, le gore et le politiquement correct.', 'https://m.media-amazon.com/images/M/MV5BODZlYzc2ODYtYmQyZS00ZTM4LTk4ZDQtMTMyZDdhMDgzZTU0XkEyXkFqcGdeQXVyMzQ2MDI5NjU@._V1_SY1000_CR0,0,666,1000_AL_.jpg', 1, '', 0);
insert into program (id, title, synopsis, poster, category_id, country, year) values (4, 'Love Death And Robots', 'Un yaourt susceptible, des soldats lycanthropes, des robots déchaînés, des monstres-poubelles, des chasseurs de primes cyborgs, des araignées extraterrestres et des démons assoiffés de sang : tout ce beau monde est réuni dans 18 courts métrages animés déconseillés aux âmes sensibles.', 'https://m.media-amazon.com/images/M/MV5BMTc1MjIyNDI3Nl5BMl5BanBnXkFtZTgwMjQ1OTI0NzM@._V1_SY1000_CR0,0,674,1000_AL_.jpg', 1, '', 0);
insert into program (id, title, synopsis, poster, category_id, country, year) values (5, 'Penny Dreadful', 'Dans le Londres ancien, Vanessa Ives, une jeune femme puissante aux pouvoirs hypnotiques, allie ses forces à celles de Ethan, un garçon rebelle et violent aux allures de cowboy, et de Sir Malcolm, un vieil homme riche aux ressources inépuisables. Ensemble, ils combattent un ennemi inconnu, presque invisible, qui ne semble pas humain et qui massacre la population.', 'https://m.media-amazon.com/images/M/MV5BNmE5MDE0ZmMtY2I5Mi00Y2RjLWJlYjMtODkxODQ5OWY1ODdkXkEyXkFqcGdeQXVyNjU2NjA5NjM@._V1_SY1000_CR0,0,695,1000_AL_.jpg', 1, '', 0);
insert into program (id, title, synopsis, poster, category_id, country, year) values (6, 'Fear The Walking Dead', 'La série se déroule au tout début de l épidémie relatée dans la série mère The Walking Dead et se passe dans la ville de Los Angeles, et non à Atlanta. Madison est conseillère dans un lycée de Los Angeles. Depuis la mort de son mari, elle élève seule ses deux enfants : Alicia, excellente élève qui découvre les premiers émois amoureux, et son grand frère Nick qui a quitté la fac et a sombré dans la drogue.', 'https://m.media-amazon.com/images/M/MV5BYWNmY2Y1NTgtYTExMS00NGUxLWIxYWQtMjU4MjNkZjZlZjQ3XkEyXkFqcGdeQXVyMzQ2MDI5NjU@._V1_SY1000_CR0,0,666,1000_AL_.jpg', 1, '', 0);

-- Seasons
insert into season (id, program_id, number, year, description) values (1, 1, 1, 2010, 'Après une épidémie post-apocalyptique ayant transformé la quasi-totalité de la population américaine et mondiale en mort-vivants ou « rôdeurs », un groupe d''hommes et de femmes mené par l''adjoint du shérif du comté de Kings (en Géorgie) USA, Rick Grimes, tente de survivre…

Ensemble, ils vont devoir tant bien que mal faire face à ce nouveau monde devenu méconnaissable, à travers leur périple dans le Sud profond des États-Unis.');
insert into season (id, program_id, number, year, description) values (2, 1, 2, 2012, 'À la suite de l''explosion du CDC, le groupe de survivants mené par Rick Grimes arrive à la ferme des Greene pour survivre aux rôdeurs.');
insert into season (id, program_id, number, year, description) values (3, 1, 3, 2013, 'Après avoir été contraint de quitter en hâte la ferme de Hershel sous l''assaut des rôdeurs, le petit groupe erre péniblement dans un monde de plus en plus chaotique et dangereux, tandis que la grossesse de Lori arrive bientôt à son terme. Par hasard, Rick découvre un endroit potentiellement sûr : une prison. Lui et les siens décident alors d''y prendre leurs quartiers. De son côté, Andrea, qui a été laissée pour morte par le groupe après l''incendie de la ferme, s''est fait une nouvelle amie en la personne de Michonne.');
insert into season (id, program_id, number, year, description) values (4, 1, 4, 2014, 'Plusieurs mois après les derniers évènements, les occupants de la prison, qui ont réussi à la sécuriser à nouveau depuis la disparition du Gouverneur, accueillent désormais une grande population de survivants et la vie reprend peu à peu son cours. Toutefois, les épreuves de Woodbury ont laissé des traces : Rick, qui n''est plus que « l''ombre de lui-même », refuse de porter son arme, allant même jusqu’à céder sa place de leader au sein du groupe à un Conseil qui se compose de Hershel, Sasha, Glenn, Daryl et Carol. Michonne quant à elle est déterminée à trouver et à tuer le Gouverneur pour venger la mort d''Andrea.

Un autre problème vient s''additionner à la vie des occupants : une épidémie commence à se propager à l''intérieur de la prison, touchant et tuant de nombreuses personnes, lesquelles se transforment peu après en rôdeurs. Dans l''urgence, ils prennent la décision de mettre les malades en quarantaine. Karen, la petite amie de Tyreese, qui a été touchée par l’épidémie, est retrouvée morte, le corps entièrement brûlé. Cette découverte affecte profondément Tyreese, qui exige de Rick des explications. Dans sa rage, Tyreese s''en prend à Rick mais celui-ci riposte avec une telle violence qu''il se blesse à la main droite.

Dehors, la situation empire, les rôdeurs, toujours plus nombreux, s''agglutinent contre la grille et risquent de la faire céder à tout moment, tandis que le Gouverneur, plein de rancune à l''égard de Rick, veut sa revanche.');
insert into season (id, program_id, number, year, description) values (5, 1, 5, 2015, 'Rick et sa troupe ont fui le terminus et errent dans la nature jusqu''à être recueillis par un pasteur dans son église puis dans le lieu recherché de tous : Alexandria Safe Zone.');
insert into season (id, program_id, number, year, description) values (6, 1, 6, 2016, 'À Alexandria, la population est coupée en deux : les partisans de Rick, qui a su se montrer impitoyable face au danger et les partisans de Morgan, plus modérés, menés par Deanna. Daryl n''est pas certain de savoir à qui se fier.

Tandis qu''une guerre civile les menace, les rôdeurs s''amassent aux portes de la ville et les « Wolves » sont eux aussi sur la piste d''Alexandria. Les rôdeurs franchissent une nouvelle étape en termes de décomposition.

Pour les anciens habitants d''Alexandria, c''est la fin d''une utopie. Il n''y aura pas de retour à une vie normale.

Ils rencontrent ensuite des survivants, une nouvelle communauté retranchée dans une colline qui sont confrontés à un autre groupe armé qui se nomme « les sauveurs ». Rick, déterminé, décide de les éliminer cependant cela se termine par la capture de Rick et de son groupe. Dirigé d''une main de fer par leur leader qui se nomme Negan, celui-ci leur inflige une punition qui se traduit par la mise à mort d''un des membres du groupe…');
insert into season (id, program_id, number, year, description) values (7, 1, 7, 2017, 'Après la sanglante mise à mort de Glenn et d''Abraham, Negan et ses "sauveurs" dominent désormais les communautés d''Alexandria, la Colline et le Royaume. C''est le commencement d''une longue période de soumission et d''humiliation de la part du terrible leader.');
insert into season (id, program_id, number, year, description) values (8, 1, 8, 2018, 'Après une longue période de soumission et d’humiliation, Rick et sa bande déclarent la guerre à Negan et ne reculeront désormais devant rien pour l’emporter.');
insert into season (id, program_id, number, year, description) values (9, 1, 9, 2019, 'Un an et demi après la terrible guerre qui a opposé l''Alliance menée par Rick et les Sauveurs menés par Negan, la vie semble s''être apaisée et un semblant de civilisation commence à renaître grâce aux travaux de Rick. Mais la cohabitation avec les Sauveurs reste remplie de tensions et certains ont du mal à s''y habituer. Tandis que les tensions grandissent de plus en plus, personne n''aperçoit le véritable danger qui se profile à leur insu et qui va changer l''installation de leur « nouvelle vie ». Menés par Alpha et Beta, les « Chuchoteurs » approchent.');
insert into season (id, program_id, number, year, description) values (10, 1, 10, 2020, 'Après la fin de l''hiver, les communautés unies sont toujours aux prises avec les effets de l''attaque mortelle des "chuchoteurs". Une bataille paraît inévitable.');


-- Episodes
insert into episode (id, season_id, title, number, synopsis) values (1, 1, 'Passé décomposé', 1, 'Rick Grimes, shérif, est blessé à la suite d''une course-poursuite. Il se retrouve dans le coma. Cependant, lorsqu''il se réveille dans l''hôpital, il ne découvre que désolation et cadavres. Se rendant vite compte qu''il est seul, il décide d''essayer de retrouver sa femme Lori et son fils Carl. Lorsqu''il arrive chez lui, il s''aperçoit que sa maison est vide et que sa famille a disparu. Puis en ressortant de chez lui, il reçoit un coup sur la tête et tombe inconscient. Rick a en fait été assommé par Duane, le fils de Morgan, un médecin qui l''avait pris pour un zombie . Rick est désorienté lorsque Morgan lui apprend que l''humanité a été décimée par un phénomène étrange qui transforme les humains en errants. Il apprend comment le père et son fils font pour survivre (éviter la lumière et le bruit qui attirent les zombies). Le lendemain, Rick accompagne Morgan et Duane au commissariat pour leur donner des armes afin de se défendre, en prendre pour lui, et les munir, lui et Morgan, de talkie-walkie dans le but de rester en contact. Rick décide de partir pour Atlanta où il est persuadé que son fils et sa femme sont, car Morgan a entendu une rumeur selon laquelle il y aurait un camp de réfugiés. Les trois survivants promettent de se retrouver plus tard. Lorsque Rick se dirige vers la ville, il découvre que les rues sont jonchées de cadavres, mais aussi remplies de rôdeurs. Rick est dépassé, il laisse tomber son sac d''armes au milieu de la rue, et se réfugie dans un tank. C''est alors qu''une voix retentit dans la radio du char.');
insert into episode (id, season_id, title, number, synopsis) values (2, 1, 'Tripes', 2, 'Rick parvient à s''échapper du tank grâce à l''aide de Glenn, dont il avait entendu la voix à la radio. Rick et Glenn se réunissent avec les compagnons de Glenn, un autre groupe de survivants dont Andrea, T-dog, Merle, Morales, Jacqui, venus pour se ravitailler au supermarché. Cependant, l''arrivée mouvementée de Rick les met tous en péril, l''attention des zombies ayant été attirée sur leur cachette. Assiégé par les zombies, le groupe parvient brièvement à communiquer par radio avec le groupe de Shane et Lori, mais ceux-ci décident qu''ils ne peuvent les aider, la présence de Rick ne leur ayant pas encore été communiquée. Dans le petit groupe cloîtré à l''intérieur du supermarché, les tensions s''exacerbent, particulièrement entre T-Dog, un noir et Merle Dixon, un blanc raciste, ce qui conduit Rick à intervenir en menottant Merle à un tuyau sur le toit du magasin. Rick, Andréa et Glenn planifient leur évasion du magasin toujours assiégé, l''idée est de se couvrir des lambeaux de chair et des boyaux des cadavres pour masquer leur odeur trop reconnaissable afin de pouvoir circuler parmi les zombies et atteindre des camions. Malgré la pluie qui a failli contrarier ce plan, le groupe parvient à s''échapper, dans un fourgon Dodge pour Andrea, Jacquie, T-Dog, Morales et Rick et une voiture pour Glenn. Seul Merle manque à l''appel après que T-Dog a accidentellement perdu la clé dans une canalisation, laissant Merle attaché au tuyau. Seule précaution : la porte d''accès au toit a été cadenassée pour préserver autant que possible Merle des rôdeurs…');
insert into episode (id, season_id, title, number, synopsis) values (3, 1, 'Les Grenouilles', 3, 'De retour au camp avec le groupe de survivants du supermarché, Rick retrouve enfin et avec beaucoup d''émotion sa femme Lori et son fils Carl. Andrea quant à elle, rejoint sa jeune sœur Amy. Mais très vite, malgré l''intrusion d''un zombie près du camp, Rick décide, contre l''avis de Shane, de retourner à Atlanta chercher Merle Dixon ainsi que son sac d''armes abandonné en route et récupérer au passage le talkie-walkie laissé dans le sac et ainsi prévenir Morgan de ne pas se rendre dans le piège d''Atlanta. Il est accompagné de Daryl Dixon, le frère de Merle, plus jeune mais tout aussi violent, ainsi que Glenn qui connaît bien les lieux et T-Dog qui se sent redevable et Andrea. Lori prévient Shane de rester à distance de sa famille maintenant que Rick est de retour, car Shane lui avait dit que Rick était mort à l''hôpital. Les tensions s''exacerbent au camp entre une femme, Carole et son mari violent, Ed. Amy intervient pour prendre la défense de Carole avant qu''une bagarre éclate, au cours de laquelle Shane donne libre cours à sa colère. Il frappe Ed jusqu''à presque le tuer, ce qui effraie plusieurs témoins de la scène. L''équipe de rescousse parvient à Atlanta mais une fois arrivée sur le toit, elle découvre que Merle a utilisé une scie pour se couper la main et se libérer des menottes. Il a visiblement perdu beaucoup de sang mais reste introuvable…');
insert into episode (id, season_id, title, number, synopsis) values (4, 1, 'Le gang', 4, 'En cherchant Merle, le groupe essaie aussi, par la même occasion, de retrouver le sac d''armes mais un autre groupe de survivants, également en quête des armes, les attaque. Le groupe parvient à capturer un attaquant blessé, Miguelito, mais les autres assaillants s''enfuient en voiture en emmenant Glenn comme otage. Après l''interrogatoire de leur otage, Rick et ses camarades apprennent le lieu de la cachette de leurs opposants et espèrent procéder à un échange de prisonniers. Le deuxième groupe dirigé par leur chef Guillermo, alias « G », refuse, exigeant le sac d''armes en plus du prisonnier. Le bain de sang est évité grâce à l''arrivée d''une personne âgée (la grand-mère d''un des hispaniques) qui met fin à la confrontation. Rick Grimes et ses compagnons se rendent compte que l''image belliqueuse que leurs hôtes se donnent n''est qu''une façade : ce « gang » est en fait constitué d''anciens employés d''un pensionnat reculé de personnes âgées encore occupé par les pensionnaires, ainsi que de membres de leurs familles, qui se cachent et tentent de se protéger des attaques de rôdeurs. Rick leur laisse quelques armes pour leur défense et chaque groupe repart de son côté, au complet. Au moment de reprendre le fourgon, ils découvrent que Merle l''a volé et a ramené une dizaines de rodeur au camps. Plusieurs membres sont tués, dont Amy, la jeune sœur d''Andrea et Ed, le mari de Carole. Le groupe de Rick arrive au camp juste à temps pour éliminer les derniers rôdeurs et sauver le reste du groupe. Avant ça, un des membres du groupe, Jim, avait fait un rêve où il creusait des trous dans la terre mais à son réveil il ne se souvient plus pourquoi il creusait. Au moment de l''attaque, il s''en est souvenu : c''était pour enterrer les morts du groupe.');
insert into episode (id, season_id, title, number, synopsis) values (5, 1, 'Feu de forêt', 5, 'Les cadavres sont enterrés, ceux des rôdeurs brûlés, mais Andrea protège le corps d''Amy jusqu''à son réveil en rôdeur , pour finir par l''achever. Dale, la voyant totalement bouleversée, tente en vain de la réconforter. Jim, un des survivants, révèle qu''il a été mordu par un rôdeur durant l''attaque et les membres du groupe décident de l''amener au Centre pour le contrôle et la prévention des maladies, dans l''espoir d''y trouver un vaccin. Mais ce projet est une source de conflit entre Shane et Rick, Shane étant persuadé que le CDC sera une impasse. Une seule famille, les Morales, se sépare du groupe, décidant de retourner dans leur famille à Birmingham, Alabama et les membres restants partent pour le CDC. Mais durant le trajet, l''état de Jim empire et celui-ci demande aux autres de le laisser mourir seul dans la forêt. Le groupe arrive ensuite à l''immeuble du CDC, dans lequel un scientifique, Edwin Jenner, s''est enfermé pour poursuivre des tests sur le virus des zombies. Il vient juste de perdre son seul échantillon de test du virus et annonce à la caméra qui le surveille (mais y a-t-il encore quelqu''un de l''autre côté ?) qu''il envisage de se suicider. Au moment où le groupe se prépare à partir, croyant l''immeuble vide, Rick remarque qu''une caméra bouge et il supplie qu''on le laisse entrer avec son groupe. Les portes s''ouvrent alors à la stupéfaction du groupe de survivants.');
insert into episode (id, season_id, title, number, synopsis) values (6, 1, 'Sujet-test 19', 6, 'Edwin Jenner accueille les survivants au CDC. Le petit groupe profite d''un repos provisoire. Andrea reste dans un état dépressif et Dale tente vainement de la réconforter. Après un repas et une nuit de repos, Jenner leur explique ce qu''il sait de la situation en leur montrant la vidéo de l''évolution du Sujet-Test 19. À la fin de la video, les survivants remarquent un compte à rebours, Jenner leur explique que c''est le temps restant avant l''extinction du groupe électrogène. Les survivants apprennent qu''à la fin de ce délai, tout le CDC sera détruit. La tension monte alors entre ceux qui veulent rester pour mourir et ceux qui veulent tenter leur chance dans le monde extérieur, infesté de morts-vivants. Finalement Jacquie reste avec Jenner, le reste du groupe parvenant, de justesse, à sortir du bâtiment, afin de se mettre en route vers une destination inconnue.');
